/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.Vistas;

import com.unab.edu.DAO.clsUsuario;
import com.unab.edu.Entidades.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author dayan
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnCerrarLogin = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        btnEntrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cancelar(3).png"))); // NOI18N
        btnCerrarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarLoginMouseClicked(evt);
            }
        });
        jPanel2.add(btnCerrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 20, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/banco.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 130, 140));

        jLabel6.setFont(new java.awt.Font("Gadugi", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Banco Primero");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 220, 470));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Gadugi", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(24, 161, 24));
        jLabel7.setText("Iniciar Sesión");

        jLabel8.setFont(new java.awt.Font("Gadugi", 0, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(24, 161, 24));
        jLabel8.setText("Usuario");

        jLabel9.setFont(new java.awt.Font("Gadugi", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(24, 161, 24));
        jLabel9.setText("Clave");

        txtUsuario.setBackground(new java.awt.Color(218, 213, 213));
        txtUsuario.setFont(new java.awt.Font("Gadugi", 0, 13)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setBorder(null);

        txtClave.setBackground(new java.awt.Color(218, 213, 213));
        txtClave.setFont(new java.awt.Font("Gadugi", 0, 13)); // NOI18N
        txtClave.setForeground(new java.awt.Color(102, 102, 102));
        txtClave.setBorder(null);

        cmbTipoUsuario.setBackground(new java.awt.Color(218, 213, 213));
        cmbTipoUsuario.setFont(new java.awt.Font("Gadugi", 0, 13)); // NOI18N
        cmbTipoUsuario.setForeground(new java.awt.Color(102, 102, 102));
        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTipoUsuario.setBorder(null);

        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnEntrar.png"))); // NOI18N
        btnEntrar.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtClave, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.Alignment.LEADING, 0, 358, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(btnEntrar)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnEntrar)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarLoginMouseClicked
   
    }//GEN-LAST:event_btnCerrarLoginMouseClicked

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        clsUsuario UsuarioDao = new clsUsuario();
        Usuario usu = new Usuario();
        usu.setUsuario(txtUsuario.getText());
        usu.setPassword(txtClave.getText());
        int tipo = 0;
        if (!usu.getUsuario().isEmpty() && !usu.getPassword().isEmpty()) {
            if (opcUsuario.isSelected()) {
                tipo = 2;
            } else if (opcAdmin.isSelected()) {
                tipo = 1;
            }
            if (tipo != 0) {
                usu.setTipoUsuario(tipo);
                Usuario user= new Usuario();
                user=UsuarioDao.Login(usu);
                if(user.getUsuario()!=null){
                    JOptionPane.showMessageDialog(null, "BIENVENIDO " + user.getUsuario());
                }else{
                    JOptionPane.showMessageDialog(null, "No se encontró el usuario" + "Intente de nuevo");
                }
                usu=user;
                if (user.getTipoUsuario() == 1) {
                    
                    FrmCajero frmcajero = new FrmCajero();
                    frmcajero.setVisible(true);
                    this.hide();
                } else if(user.getTipoUsuario() == 2){
                    
                    
                    FrmAdmin frmadmin = new FrmAdmin();
                    frmadmin.setVisible(true);
                    this.hide();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Complete los campos");
            }
        } else {

            JOptionPane.showMessageDialog(null, "Complete los campos");
        }
        
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }
        
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCerrarLogin;
    private javax.swing.JLabel btnEntrar;
    private javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
